# Generated by Django 5.1.7 on 2025-04-06 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_booking_app', '0002_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='image_upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=255, null=True)),
                ('movie_type', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
