# Generated by Django 5.1.7 on 2025-04-07 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_booking_app', '0003_image_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='image_upload',
            name='language',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
