# Generated by Django 5.1.7 on 2025-04-08 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_booking_app', '0006_sports_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='cinemas_upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cinemas_name', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
