# Generated by Django 5.1.7 on 2025-04-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_booking_app', '0008_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='username',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
