# Generated by Django 5.1.7 on 2025-04-13 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_booking_app', '0009_booking_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='username',
            new_name='cinema_name',
        ),
        migrations.AddField(
            model_name='booking',
            name='language',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='movie_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
