# Generated by Django 5.1.7 on 2025-04-13 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show_booking_app', '0010_rename_username_booking_cinema_name_booking_language_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='cinema_name',
            new_name='cinema',
        ),
    ]
