# Generated by Django 5.1.7 on 2025-04-13 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_booking_app', '0011_rename_cinema_name_booking_cinema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='cinema',
        ),
        migrations.AddField(
            model_name='booking',
            name='cinema_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
