# Generated by Django 5.1.7 on 2025-04-13 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_booking_app', '0012_remove_booking_cinema_booking_cinema_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('language', models.CharField(max_length=255, null=True)),
                ('movie_type', models.CharField(max_length=255, null=True)),
                ('cinema_name', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='booking',
        ),
    ]
