# Generated by Django 5.1.7 on 2025-04-15 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_booking_app', '0014_rename_cinema_name_book_cinemas_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='username',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
