# Generated by Django 5.1.7 on 2025-04-15 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show_booking_app', '0015_book_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='username',
        ),
    ]
