# Generated by Django 5.1.7 on 2025-04-17 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_booking_app', '0019_remove_book_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
