# Generated by Django 5.1.7 on 2025-04-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_booking_app', '0020_book_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='sports_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
