# Generated by Django 5.1.7 on 2025-04-23 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_booking_app', '0021_book_sports_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='seats',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
