# Generated by Django 5.1.7 on 2025-04-23 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show_booking_app', '0023_alter_book_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='seats',
        ),
    ]
