# Generated by Django 5.1.7 on 2025-04-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_booking_app', '0024_remove_book_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='seats',
            field=models.IntegerField(null=True),
        ),
    ]
