# Generated by Django 5.1.7 on 2025-04-30 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_booking_app', '0025_book_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='user',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
