# Generated by Django 5.2.3 on 2025-06-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_booking_app', '0026_book_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(null=True, upload_to='movies/'),
        ),
        migrations.AlterField(
            model_name='events_upload',
            name='image',
            field=models.ImageField(upload_to='movies/'),
        ),
        migrations.AlterField(
            model_name='image_upload',
            name='image',
            field=models.ImageField(upload_to='movies/'),
        ),
        migrations.AlterField(
            model_name='sports_upload',
            name='image',
            field=models.ImageField(upload_to='movies/'),
        ),
    ]
