# Generated by Django 5.2.5 on 2025-08-11 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_booking_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='signup',
            new_name='sign',
        ),
    ]
