# Generated by Django 5.2.5 on 2025-08-11 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_booking_app', '0002_rename_signup_sign'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sign',
        ),
    ]
