# Generated by Django 5.2.5 on 2025-08-13 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ticket_booking_app', '0003_delete_sign'),
    ]

    operations = [
        migrations.CreateModel(
            name='movies_upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=255, null=True)),
                ('image', models.ImageField(upload_to='movie/')),
                ('title', models.CharField(max_length=255, null=True)),
                ('movie_type', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
