# Generated by Django 5.2.5 on 2025-08-16 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_booking_app', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cinemas_upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cinemas_name', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
