# Generated by Django 5.2.4 on 2025-08-20 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_booking_app', '0005_cinemas_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255, null=True)),
                ('image', models.ImageField(null=True, upload_to='movies/')),
                ('title', models.CharField(max_length=255, null=True)),
                ('language', models.CharField(max_length=255, null=True)),
                ('movie_type', models.CharField(max_length=255, null=True)),
                ('cinemas_name', models.CharField(max_length=255, null=True)),
                ('location', models.CharField(max_length=255, null=True)),
                ('seats', models.IntegerField(null=True)),
            ],
        ),
    ]
