# Generated by Django 5.2.4 on 2025-08-21 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_booking_app', '0006_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='sports_upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='movies/')),
                ('title', models.CharField(max_length=255, null=True)),
                ('location', models.CharField(max_length=255, null=True)),
                ('sports_type', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
