# Generated by Django 5.2.4 on 2025-08-21 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_booking_app', '0007_sports_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='sports_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
