# Generated by Django 5.2.5 on 2025-08-22 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_booking_app', '0002_create_admin'),
        ('ticket_booking_app', '0008_book_sports_type'),
    ]

    operations = [
    ]
